# Generated by Django 5.1.2 on 2024-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('top_level_domain', models.CharField(blank=True, max_length=10, verbose_name='Топ-уровневый домен')),
                ('alpha2_code', models.CharField(max_length=2, unique=True, verbose_name='Двухбуквенный код страны')),
                ('alpha3_code', models.CharField(max_length=3, unique=True, verbose_name='Трехбуквенный код страны')),
                ('calling_code', models.CharField(blank=True, max_length=5, verbose_name='Телефонный код')),
                ('capital', models.CharField(blank=True, max_length=100, verbose_name='Столица')),
                ('alt_spellings', models.TextField(blank=True, verbose_name='Альтернативные написания')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Регион')),
            ],
        ),
    ]
