# Generated by Django 5.1.2 on 2024-10-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Двухбуквенный код страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Трехбуквенный код страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='calling_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефонный код'),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=255, verbose_name='Столица'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='country',
            name='top_level_domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Топ-уровневый домен'),
        ),
    ]
