# Generated by Django 5.1.2 on 2024-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Двухбуквенный код страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Трехбуквенный код страны'),
        ),
    ]
