version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - backend

  country-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py posts_scheduler
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - backend
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
