# Generated by Django 5.1.2 on 2024-10-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_alter_country_alpha2_code_alter_country_alpha3_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.IntegerField(default=0, verbose_name='Количество подписчиков')),
                ('is_create', models.BooleanField(default=False, verbose_name='Создавать посты')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('countries_interest', models.ManyToManyField(blank=True, to='country.country', verbose_name='Интересующие страны')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
