# Generated by Django 5.1.2 on 2024-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_count',
            field=models.IntegerField(default=0, verbose_name='Количество постов'),
        ),
    ]
