# Generated by Django 5.1.2 on 2024-10-21 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_photo_options_alter_post_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postratingaction',
            unique_together={('user', 'post', 'action')},
        ),
    ]
