# Generated by Django 5.1.2 on 2024-10-22 05:28

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_postratingaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_lifted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее время поднятия'),
        ),
        migrations.CreateModel(
            name='AutoPostLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала автоподнятия')),
                ('end_date', models.DateField(verbose_name='Дата окончания автоподнятия')),
                ('days_of_week', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=13, verbose_name='Дни недели для автоподнятия')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_lifts', to='user.post')),
            ],
            options={
                'verbose_name': 'Автоподнятие поста',
                'verbose_name_plural': 'Автоподнятие постов',
            },
        ),
        migrations.CreateModel(
            name='PostLiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время поднятия')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lift_logs', to='user.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Лог автоподнятия поста',
                'verbose_name_plural': 'Логи автоподнятия постов',
            },
        ),
    ]
